### ISSUE TITLE
Site doesn't render correctly on smaller screens (mobile devices)

### ISSUE THREAD

**Issue by benhayehudi** [benhayehudi/portfolio-site-client#1]
The following are issues when viewing the site on a mobile device:

Main Page:
1. The header doesn't format correctly
2. The main content area is cut off on top by the navbar

Portfolio Page, Blog Pages and Contact Page:
1. The header doesn't format correctly
2. The Navbar is sitting on top of the content body

**Comment by SoerenTerh** [comment]
PR coming in in a moment.
